Add EncryptionCeasar and Program
BaseWebDev/HT_7 pull request #1
Opened 2018-04-27 11:02 UTC by SermusAnton

EncryptionCeasar

2018-04-29 09:52 UTC, ilpoli requested changes

2018-04-29 09:52 UTC, ilpoli commented on CeasarCipher/EncryptionCeasar.cs
> +        public string CloseString {
холиварный вопрос когда использовать методы а когда использовать свойства, mictosoft говорит https://msdn.microsoft.com/en-us/library/ms229054%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396
в твоем случае шифрование долгий процесс, по этому лучше использовать метод.
>The operation is orders of magnitude slower than a field set would be. If you are even considering providing an asynchronous version of an operation to avoid blocking the thread, it is very likely that the operation is too expensive to be a property. In particular, operations that access the network or the file system (other than once for initialization) should most likely be methods, not properties.

2018-04-29 09:52 UTC, ilpoli commented on CeasarCipher/EncryptionCeasar.cs
> +                if (value == 0) {
Вот отличный пример свойства.

2018-04-29 09:52 UTC, ilpoli commented on CeasarCipher/EncryptionCeasar.cs
> +            string bufString = "";
По моему Decrypt должен быть равен Crypt, разве только что ключ не прибавляется а вычитается

2018-05-08 21:30 UTC, SermusAnton commented
Исправил

2018-05-09 07:41 UTC, ilpoli approved these changes

2018-05-09 19:52 UTC, merged